apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-service-config
  namespace: agricultural-system
data:
  NODE_ENV: "production"
  PORT: "3003"
  MONGODB_URI: "mongodb://admin:mongopassword123@mongodb-service:27017/agricultural_sensors?authSource=admin"
  SENSOR_API_URL: "https://sensores-async-api.onrender.com/api/sensors/all"
  BATCH_SIZE: "1000"
  CONCURRENT_WORKERS: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: agricultural-system
  labels:
    app: ingestion-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
        version: v1
    spec:
      containers:
      - name: ingestion-service
        image: ghcr.io/your-org/ingestion-service:latest
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ingestion-service-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ingestion-service-config
              key: PORT
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: ingestion-service-config
              key: MONGODB_URI
        - name: SENSOR_API_URL
          valueFrom:
            configMapKeyRef:
              name: ingestion-service-config
              key: SENSOR_API_URL
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: ingestion-service-config
              key: BATCH_SIZE
        - name: CONCURRENT_WORKERS
          valueFrom:
            configMapKeyRef:
              name: ingestion-service-config
              key: CONCURRENT_WORKERS
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: agricultural-system
spec:
  selector:
    app: ingestion-service
  ports:
  - port: 3003
    targetPort: 3003
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingestion-service-hpa
  namespace: agricultural-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingestion-service
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
